project:
  type: website
  resources:
    - favicon.ico

website:
  title: "SpenceForce"
  site-url: https://www.spenceforce.io
  description: Spencer Mitchell's personal website.
  search: true
  back-to-top-navigation: true
  open-graph: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: https://nlpbook.spenceforce.io
        text: NLP Book
      - blog.qmd
      - faq.qmd
        text: FAQ
    tools:
      - icon: envelope-at
        href: mailto:smitchell556@gmail.com
      - icon: linkedin
        href: https://www.linkedin.com/in/spencerjmitchell/
      - icon: github
        href: https://github.com/spenceforce
      - icon: rss
        href: blog.xml

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    email-obfuscation: javascript

execute:
  freeze: auto

theme:
  light: flatly
  dark: darkly
