project:
  type: website

website:
  title: "SpenceForce"
  site-url: https://www.spenceforce.io
  description: NLP and data science from simple to spectactular
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/spenceforce
      - icon: twitter
        href: https://twitter.com/spence_force
      - icon: rss
        href: index.xml
format:
  html:
    theme: cosmo
    css: styles.css



