project:
  type: website

website:
  title: "SpenceForce"
  site-url: https://www.spenceforce.io
  description: Spencer Mitchell's personal website.
  search: true
  back-to-top-navigation: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: https://nlpbook.spenceforce.io
        text: NLP Book
      - blog.qmd
    right:
      - icon: rss
        href: blog.xml

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto
